/*
 * CAD Cloud Ingest API
 * CAD Ingest API in Azure cloud
 *
 * OpenAPI spec version: 1.0.0
 * Contact: onemobileapiarchitects@motorolasolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.motorola.api.auth;

import com.motorola.api.utils.Pair;

import com.migcomponents.migbase64.Base64;

import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.List;

public class HttpBasicAuth implements Authentication {

	private String username;
	private String password;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
		if (username == null && password == null) {
			return;
		}
		String str = (username == null ? "" : username) + ":" + (password == null ? "" : password);
		headerParams.put("Authorization", "Basic " + Base64.encodeToString(str.getBytes(StandardCharsets.UTF_8), false));
	}
}
