/*
 * CAD Cloud Ingest API
 * CAD Ingest API in Azure cloud
 *
 * OpenAPI spec version: 1.0.0
 * Contact: onemobileapiarchitects@motorolasolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.motorola.api.auth;

public enum OAuthFlow {
	accessCode, implicit, password, application
}
