/*
 * CAD Cloud Bulk Update API
 * CAD Bulk Update API in Azure cloud
 *
 * OpenAPI spec version: 1.0.0
 * Contact: onemobileapiarchitects@motorolasolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.motorola.models.representation;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL;

/**
 * RefreshUnitData
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(NON_NULL)
public class RefreshUnitData implements Serializable {

	@JsonProperty("unitList")
	private List<Unit> unitList = new ArrayList<Unit>();

	@JsonProperty("isFirstBatchUpdate")
	private Boolean isFirstBatchUpdate = null;

	@JsonProperty("isLastBatchUpdate")
	private Boolean isLastBatchUpdate = null;

	public RefreshUnitData unitList(List<Unit> unitList) {
		this.unitList = unitList;
		return this;
	}

	public RefreshUnitData addUnitListItem(Unit unitListItem) {
		this.unitList.add(unitListItem);
		return this;
	}

	/**
	 * List of Unit object
	 * @return unitList
	 **/
	public List<Unit> getUnitList() {
		return unitList;
	}

	public void setUnitList(List<Unit> unitList) {
		this.unitList = unitList;
	}

	public RefreshUnitData isFirstBatchUpdate(Boolean isFirstBatchUpdate) {
		this.isFirstBatchUpdate = isFirstBatchUpdate;
		return this;
	}

	/**
	 * If the data is send in batches this will be send true if its last batch
	 * @return isFirstBatchUpdate
	 **/
	public Boolean isIsFirstBatchUpdate() {
		return isFirstBatchUpdate;
	}

	public void setIsFirstBatchUpdate(Boolean isFirstBatchUpdate) {
		this.isFirstBatchUpdate = isFirstBatchUpdate;
	}

	public RefreshUnitData isLastBatchUpdate(Boolean isLastBatchUpdate) {
		this.isLastBatchUpdate = isLastBatchUpdate;
		return this;
	}

	/**
	 * If the data is send in batches this will be send true if its last batch
	 * @return isLastBatchUpdate
	 **/
	public Boolean isIsLastBatchUpdate() {
		return isLastBatchUpdate;
	}

	public void setIsLastBatchUpdate(Boolean isLastBatchUpdate) {
		this.isLastBatchUpdate = isLastBatchUpdate;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RefreshUnitData refreshUnitData = (RefreshUnitData) o;
		return Objects.equals(this.unitList, refreshUnitData.unitList) &&
			Objects.equals(this.isFirstBatchUpdate, refreshUnitData.isFirstBatchUpdate) &&
			Objects.equals(this.isLastBatchUpdate, refreshUnitData.isLastBatchUpdate);
	}

	@Override
	public int hashCode() {
		return Objects.hash(unitList, isFirstBatchUpdate, isLastBatchUpdate);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RefreshUnitData {\n");

		sb.append("    unitList: ").append(toIndentedString(unitList)).append("\n");
		sb.append("    isFirstBatchUpdate: ").append(toIndentedString(isFirstBatchUpdate)).append("\n");
		sb.append("    isLastBatchUpdate: ").append(toIndentedString(isLastBatchUpdate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
