/*
 * CAD Cloud Bulk Update API
 * CAD Bulk Update API in Azure cloud
 *
 * OpenAPI spec version: 1.0.0
 * Contact: onemobileapiarchitects@motorolasolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.motorola.models.representation;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL;

/**
 * RefreshIncidentData
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(NON_NULL)
public class RefreshIncidentData implements Serializable {

	@JsonProperty("emergencyIncidentList")
	private List<EmergencyIncident> emergencyIncidentList = new ArrayList<EmergencyIncident>();

	@JsonProperty("isFirstBatchUpdate")
	private Boolean isFirstBatchUpdate = null;

	@JsonProperty("isLastBatchUpdate")
	private Boolean isLastBatchUpdate = null;

	public RefreshIncidentData emergencyIncidentList(List<EmergencyIncident> emergencyIncidentList) {
		this.emergencyIncidentList = emergencyIncidentList;
		return this;
	}

	public RefreshIncidentData addEmergencyIncidentListItem(EmergencyIncident emergencyIncidentListItem) {
		this.emergencyIncidentList.add(emergencyIncidentListItem);
		return this;
	}

	/**
	 * List of Emergency Incident object
	 * @return emergencyIncidentList
	 **/
	public List<EmergencyIncident> getEmergencyIncidentList() {
		return emergencyIncidentList;
	}

	public void setEmergencyIncidentList(List<EmergencyIncident> emergencyIncidentList) {
		this.emergencyIncidentList = emergencyIncidentList;
	}

	public RefreshIncidentData isFirstBatchUpdate(Boolean isFirstBatchUpdate) {
		this.isFirstBatchUpdate = isFirstBatchUpdate;
		return this;
	}

	/**
	 * If the data is send in batches this will be send true if its last batch
	 * @return isFirstBatchUpdate
	 **/
	public Boolean isIsFirstBatchUpdate() {
		return isFirstBatchUpdate;
	}

	public void setIsFirstBatchUpdate(Boolean isFirstBatchUpdate) {
		this.isFirstBatchUpdate = isFirstBatchUpdate;
	}

	public RefreshIncidentData isLastBatchUpdate(Boolean isLastBatchUpdate) {
		this.isLastBatchUpdate = isLastBatchUpdate;
		return this;
	}

	/**
	 * If the data is send in batches this will be send true if its last batch
	 * @return isLastBatchUpdate
	 **/
	public Boolean isIsLastBatchUpdate() {
		return isLastBatchUpdate;
	}

	public void setIsLastBatchUpdate(Boolean isLastBatchUpdate) {
		this.isLastBatchUpdate = isLastBatchUpdate;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RefreshIncidentData refreshIncidentData = (RefreshIncidentData) o;
		return Objects.equals(this.emergencyIncidentList, refreshIncidentData.emergencyIncidentList) &&
			Objects.equals(this.isFirstBatchUpdate, refreshIncidentData.isFirstBatchUpdate) &&
			Objects.equals(this.isLastBatchUpdate, refreshIncidentData.isLastBatchUpdate);
	}

	@Override
	public int hashCode() {
		return Objects.hash(emergencyIncidentList, isFirstBatchUpdate, isLastBatchUpdate);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RefreshIncidentData {\n");

		sb.append("    emergencyIncidentList: ").append(toIndentedString(emergencyIncidentList)).append("\n");
		sb.append("    isFirstBatchUpdate: ").append(toIndentedString(isFirstBatchUpdate)).append("\n");
		sb.append("    isLastBatchUpdate: ").append(toIndentedString(isLastBatchUpdate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
